baseURL = 'https://einbrodt.github.io/ba-blog/'
languageCode = 'de-de'
defaultContentLanguage = "de-de"
title = 'Der BA-föG Blog'
theme = 'hugo-blog-awesome'
[[params.socialIcons]]
name = "Rss"
url = "/ba-blog/index.xml"

[[params.socialIcons]]
name = "github"
url = "https://github.com/einbrodt"

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 1 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

  [Languages.de-de.menu]
  [[Languages.de-de.menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Startseite'
    url = '/'
    weight = 10
  [[Languages.de-de.menu.main]]
    pageRef="posts"
    name = 'Beiträge'
    url = '/posts/'
    weight = 20

[Languages.de-de.params]
  sitename = "BA-föG Blog"
  defaultColor = "dark" # set color mode: dark, light, auto
  # Setting it to 'auto' applies the color scheme based on the visitor's device color preference.If you don't specify anything, ignore this parameter, or leave it blank,
  # the default value is set to 'auto'.
  # You can take a look at layouts/index.html for more information.
  description = "Outtakes meiner Bachelorarbeit zu den Themen Digitalisierung und BAföG"
  mainSections = ['posts']
  toc = true # set to false to disable table of contents 'globally'
  tocOpen = false # set to true to open table of contents by default
  goToTop = true # set to false to disable 'go to top' button
  dateFormat = "" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.
  # See https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference for available date formats.
  rssFeedDescription = "summary" # available options: 1) summary 2) full
  # summary - includes a short summary of the blog post in the RSS feed. Generated using Hugo .Summary .
  # full - includes full blog post in the RSS feed. Generated using Hugo .Content .
  # By default (or if nothing is specified), summary is used.

[Languages.de-de.params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Der BA-föG Blog"
  name = "Nicole Einbrodt"
  description = "Outtakes meiner Bachelorarbeit zu den Themen Digitalisierung und BAföG"

# Allow to override webmanifest options
[Languages.de-de.params.webmanifest]
  name = "sitename" # will use "params.sitename" or "title" by default
  short_name = "sitename" # same as name
  start_url = "/" # will use homepage url by default
  theme_color = "#434648" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
  background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
  display = "standalone"